language: r
sudo: false
cache: packages
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env: DRAT_DEPLOY=true
  - os: osx
    osx_image: xcode9.2
  - os: osx
    osx_image: xcode7.3
    r_build_args: "--no-build-vignettes"
    r_check_args: "--ignore-vignettes --no-examples"
r_packages:
- covr
- drat
r_github_packages:
- cloudyr/travisci
after_success:
- R -q -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test
  $DRAT_DEPLOY == "true" && bash drat.sh
- R -q -e "travisci::restart_last_build('cloudyr/awspack')"
env:
  global:
    secure: NSKVHCSll8vKbWKx4azcRJPtILLLAz17o7GixgblbHGZcZrkMh20l3h/USsY2rpbqWsCmessQgJCG5D5a1DxBM00tqvSZiB8b5tkFTsXu2IibnALvEJbaEbLplqol0N/sOWiqHkUkRnYqZyVvaJhvU3/S2WCgGF1bPBmuMHdLmo=
